### ISSUE TITLE
Windows Issue: Must provide a path in /Users

### ISSUE THREAD

**Issue by lkhedlund** [getflywheel/local-addon-volumes#16]
- **Local Version**: 3.0.1
- **Windows Version**: 10.0.17134 Build 17134
- WSL Installed: Yes

Related: https://github.com/getflywheel/local-addon-volumes/issues/5

On Windows 10, when trying to use this as an add-on with Local 3.0.2, I get the error `Sorry! You must provide a path in /Users`. My local sites are all installed in C:\\Users\name\, etc. 

Let me know if you need anything else to help resolve this.

**Comment by peekstudio** [comment]
Workaround: Remapping works without issue on the previous version of the volumes add-on. I rolled back to that for now.

**Comment by endurtech** [comment]
Sorry, new to Github. I submitted a pull request which resolves the issue. See it at: https://github.com/getflywheel/local-addon-volumes/pull/19/commits/4eada46e7cd60525683a32690632982df8434062

**Comment by etarhan** [comment]
I can confirm 4eada46 indeed solved the problem for me as well. Thanks! @endurtech

**Comment by oliver-graetz** [comment]
I have the same problem. Why isn't this released more than 7 weeks after the fix was submitted?

**Comment by oliver-graetz** [comment]
@peekstudio Where can i get a the previous version? The web site doesn't provide old versions, the program doesn't, and here on Github there are only source code ZIP archives.

**Comment by Dean-Wilson** [comment]
@oliver-graetz Apologies for late reply. Go to code -> branches -> tags. Then I think it is version 1.2.1. Direct link to that would be https://github.com/getflywheel/local-addon-volumes/tree/1.2.1. Download the ZIP and you can install add on from disk by using the button from add-ons -> installed or just unzip into the right folder which will be something like C:\Users\User\AppData\Roaming\Local by Flywheel\addons (but first uninstalling the current version if you still have that installed).

**Comment by slavetotheweb** [comment]
So I am mighty confused.
Firstly this is seems to remain an issue - not yet rolled into the release you get via Local.
Second - inside Local the addon is shown as v1.3.0 - but looking here on GitHub the latest is shown as v1.2.1
Third - even if this issue were fixed, why do I have to choose a folder within C:\Users ? I'm trying to mount the app folder from another drive (as the add-on description states as a potential use-case)

**Comment by endurtech** [comment]
That is just what the dialog box states as a "potential" error, but not that C:\ is required. Should be able to mount the other drive (example D:\Users). However, the path must start with Users or Volumes, see example above. I agree, the error message is vague but I could do no better. Hope this helps.

**Comment by oliver-graetz** [comment]
Version 1.3.0 is broken. It states that the path must be in "/Users", which cannot be satisfied on Windows (even "C:\Users" doesn't work). Version 1.2.1 works without problems. I don't know why this regression in 1.3.0 hasn't been addressed with a newer version after months.

**Comment by manzoorwanijk** [comment]
> Version 1.3.0 is broken. It states that the path must be in "/Users", which cannot be satisfied on Windows (even "C:\Users" doesn't work). Version 1.2.1 works without problems. I don't know why this regression in 1.3.0 hasn't been addressed with a newer version after months.

I am also facing the same issue :(

**Comment by jameselks** [comment]
Still not fixed :_(

To revert to 1.2.1:

* Uninstall Volumes

* Close Local by Flywheel

* Download v1.2.1 ZIP file
https://github.com/getflywheel/local-addon-volumes/archive/1.2.1.zip

* Go to Local by Flywheel folder (paste in File Explorer)
`%appdata%\Local by Flywheel\addons`

* Extract ZIP file here

* Relaunch Local by Flywheel

* Go to Addons > Installed > and turn on Volumes

* Restart Local by Flywheel

You're good to go! Enjoy this ridiculous workaround.

**Comment by manzoorwanijk** [comment]
Still does not work. My **Sites Path** in NEW SITE DEFAULTS is set to **D:\\LocalSites** but I can't REMAP VOLUMES :(

**Comment by oliver-graetz** [comment]
Did you install the old version?

**Comment by manzoorwanijk** [comment]
> Did you install the old version?

Yes I did.

**Comment by oliver-graetz** [comment]
With the old version remapping in general works using Windows paths. But there is still a restriction regarding "Users" or "Volumes" as first segment of the path, and apparently it also need to be on the C: drive.

As a workaround you could create an NTFS junction or symlink from "D:\LocalSites" to "C:\Users\LocalSites". This way, you can enter a correctly formatted path into the Host Source field and still keep the actual data on your D: drive.

**Comment by manzoorwanijk** [comment]
> As a workaround you could create an NTFS junction or symlink from "D:\LocalSites" to "C:\Users\LocalSites".

That's what I am trying to do now.

**Comment by manzoorwanijk** [comment]
It doesn't work either. Actually the reason for that is the existing maps (with **D:\\** as source) are shown in volumes and Volumes addon validates all the mappings thus making them invalid.

![image](https://user-images.githubusercontent.com/18226415/62216815-1b561180-b3c7-11e9-963d-c64d51c3b785.png)

**Comment by oliver-graetz** [comment]
Your symlink must point to somewhere in "C:\Users". It worked for me then.

**Comment by manzoorwanijk** [comment]
I finally made it work by commenting out [this part](https://github.com/getflywheel/local-addon-volumes/blob/1.2.1/lib/SiteInfoVolumes.js#L240-L259) of the code. Then disable/enable the addon and relaunch Local :)

**Comment by rahulv3a** [comment]
@manzoorwanijk How did you manage to get it work? I also have my local sites in `D:\LocalSites`.

I did the following:
1. Removed v1.3.
2. Installed v1.2.1, and relaunched local.
3. Created symblink `D:\LocalSites` to `C:\Users\myuser\LocalSites`.
4. Mounted `C:\Users\myuser\LocalSites\my-site\app\public\wp-content\themes\my-theme` to `/app/public/wp-content/themes/my-theme`
5. Commented out [this part](https://github.com/getflywheel/local-addon-volumes/blob/1.2.1/lib/SiteInfoVolumes.js#L240-L259), and relaunched local.

But it doesn't seem to work. I get an error saying `(HTTP code 500) server error - error while creating mount source path '/c/Users/myuser/LocalSites/my-site/app/public/wp-content/themes/my-theme': mkdir /c/Users/myuser/LocalSites: file exists`

What am I missing?

**Comment by manzoorwanijk** [comment]
You need to comment out that code from this file:
`%AppData%\Roaming\Local by Flywheel\addons\local-addon-volumes\lib\SiteInfoVolumes.js`

**Comment by rahulv3a** [comment]
I did comment out that part from `SiteInfoVolumes.js`. After that, I got that `(HTTP code 500)...` error I mentioned in my previous comment.

**Comment by rahulv3a** [comment]
@manzoorwanijk when you get time, could you share the steps you took to get it working? It would help others who are trying to do the same on Windows 10.
